weights: zoo:cv/detection/yolov5-s/pytorch/ultralytics/coco/pruned_quant-aggressive_94?recipe_type=transfer
cfg: ../usr/local/lib/python3.8/dist-packages/sparseml/yolov5/models_v5.0/yolov5s.yaml
data: /content/Neural-Magic---Roboflow-Example-1/data.yaml
data_path: ''
hyp: ../usr/local/lib/python3.8/dist-packages/sparseml/yolov5/data/hyps/hyp.finetune.yaml
epochs: 300
batch_size: 16
gradient_accum_steps: 1
imgsz: 640
rect: false
resume: false
nosave: false
noval: false
noautoanchor: false
evolve: null
bucket: ''
cache: ram
image_weights: false
device: ''
multi_scale: false
single_cls: false
optimizer: SGD
sync_bn: false
workers: 8
project: yolov5_runs/train
name: exp
exist_ok: false
quad: false
cos_lr: false
label_smoothing: 0.0
patience: 0
freeze:
- 0
save_period: -1
local_rank: -1
entity: null
upload_dataset: false
bbox_interval: -1
artifact_alias: latest
recipe: zoo:cv/detection/yolov5-s/pytorch/ultralytics/coco/pruned_quant-aggressive_94?recipe_type=transfer
recipe_args: null
disable_ema: false
max_train_steps: -1
max_eval_steps: -1
one_shot: false
log_directory: null
save_dir: yolov5_runs/train/exp
