# example-config.yaml
loggers:
  custom_logger:
    path: roboflow-logger.py:RoboflowLogger
    api_key: 3h3KYzVY4L6cGaO1iU3E
    dataset_name: neural-magic-roboflow-example

endpoints:
  - task: yolo
    model: sparse-yolov5s.onnx
    name: yolov5
    data_logging:
      pipeline_inputs:
        - func: roboflow-logger.py:save_as_img
          frequency: 1
          target_loggers:
            - custom_logger
    